version: '3.8'

services:

  market-app:
    container_name: market-app
    extends:
      file: ./market-ms/docker-compose.yaml
      service: app
    depends_on:
      - market-db
      - market-cache
  market-db:
    container_name: market-db
    extends:
      file: ./market-ms/docker-compose.yaml
      service: db
  market-cache:
    container_name: market-cache
    extends:
      file: ./market-ms/docker-compose.yaml
      service: cache

  auth-app:
    container_name: auth-app
    extends:
      file: ./auth-ms/docker-compose.yaml
      service: app
    depends_on:
      - auth-db
  auth-db:
    container_name: auth-db
    extends:
      file: ./auth-ms/docker-compose.yaml
      service: db

  adminpanel-app:
    container_name: adminpanel-app
    extends:
      file: ./adminpanel-ms/docker-compose.yaml
      service: app
    depends_on:
      - adminpanel-db
  adminpanel-db:
    container_name: adminpanel-db
    extends:
      file: ./adminpanel-ms/docker-compose.yaml
      service: mongodb
  adminpanel-db-client:
    container_name: adminpanel-db-client
    extends:
      file: ./adminpanel-ms/docker-compose.yaml
      service: mongo-express
    depends_on:
      - adminpanel-db


  message-broker:
    image: nats:alpine3.20
    container_name: nats
    ports:
      - 4222:4222
    network_mode: "host"

  proxy:
    image: nginx:stable-alpine
    container_name: nginx-ms
    ports:
      - 80:80
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: [ "nginx", "-g", "daemon off;" ]
